### ISSUE TITLE
Cannot connect source to Heroku Postgres instances

### ISSUE THREAD

**Issue by kevin-cantwell** [pagarme/teleport#10]
Amazing tool! However Heroku requires `sslmode=require` to connect to their databases from outside. However it looks like sslmode is being explicitly disabled: https://github.com/pagarme/teleport/blob/master/database/database.go#L42

I tried forking, modifying the sslmode and still I can't connect, so forgive me as I'm not 100% sure this is the problem.

Error log:
```
source_1 | 2016/05/25 21:27:29 Erro starting database: %!(EXTRA *pq.Error=pq: no pg_hba.conf entry for host "<IP REDACTED>", user "<USER REDACTED>", database "<DATABASE REDACTED>", SSL off)
```

**Comment by kevin-cantwell** [comment]
After further testing, I realize I'm able to connect to heroku postgres by setting `sslmode=require`. However, we are using postgres version 9.2.16 and as far as I can tell teleport is only compatible with postgres >= 9.3

**Comment by pedrofranceschi** [comment]
What errors are you facing? IIRC it should work on 9.2

**Comment by kevin-cantwell** [comment]
Hi @pedrofranceschi. The `CREATE SCHEMA IF NOT EXISTS` wasn't added until 9.3: https://www.postgresql.org/docs/9.3/static/release-9-3.html. The `json_agg` function was added in 9.3 as well.

I'm testing a [fork](https://github.com/timehop/teleport) which contains [these fixes](https://github.com/timehop/teleport/commit/53ef3a890a7ecff1d5e85ea7a44371245cf76188). I also [changed the way databases are configured](https://github.com/timehop/teleport/commit/0eac59fc62ba5cf09443fa1afa6824034440bbd3) so one may specify arbitrary parameters -- such as `sslmode` -- in the connection string.

We're testing this on a production-sized db right now. Will submit a PR when we feel confident it works :)

**Comment by pedrofranceschi** [comment]
Oh yes, json_agg was indeed added on 9.3 and it is essential for DDL diffs.

That's great! Whenever you feel it is ready, send it!

**Comment by kevin-cantwell** [comment]
So I _think_ this is working well, unfortunately we're migrating from a 9.2.16 db to a 9.5 db and there's missing extensions like postgis so we haven't got a fully successful run yet. I did submit the PR though, since I believe this particular issue has been addressed.
