### ISSUE TITLE
Multi-Master Replication

### ISSUE THREAD

**Issue by lweberk** [pagarme/teleport#14]
Hi,

though there is the mention of multiple targets and master-master replication in the README and issues, I'd like to ask whether multi-master is supported. If so any deployment experiences (first-third hand knowledge)?

We have an upcoming deployment for a 1 central and roughly 10 satellites (over WAN) deployment with little actual load (satellites are POS's - ~1 write/minute) and I'm wondering whether to go for Teleport over Bucardo if possible. DDL propagation is really nice to have in this case. Also it gives kind of a rough time to trust 10k lines Perl for this, even though its one of the nicest Perl scripts I've seen so far.

Thanks,
~lwk

**Comment by pedrofranceschi** [comment]
Hi,

Multi-master replication is definitely possible, just add one more target to the target instance. A useful gotcha is obviously not to replicate the same table twice (I.e. from both source to target and target to source) - this may cause unexpected behaviors and compromise replication.

Please let me know if you have any problem.

**Comment by lweberk** [comment]
Great! Will try it out. Thanks a lot.
